### ISSUE TITLE
Redo all SVGs to avoid empty space

### ISSUE THREAD

**Issue by dankohn** [cncf/artwork#17]
This issue was first notes in #10.

**Comment by dankohn** [comment]
Cc @juliusv

**Comment by dankohn** [comment]
@juliusv @radoslaw @lukaszgryglicki Could you please confirm that the updated SVGs not look correct?

**Comment by lukaszgryglicki** [comment]
Fluentd is not square: https://github.com/cncf/artwork/blob/master/fluentd/icon/color/fluentd-icon-color.svg
gRPC is not square: https://github.com/cncf/artwork/blob/master/grpc/color/grpc-color.svg
Same with:
Envoy: https://github.com/cncf/artwork/blob/master/envoy/icon/color/envoy-icon-color.svg
Jeager: https://github.com/cncf/artwork/blob/master/jaeger/icon/color/jaeger-icon-color.svg
TUF: https://github.com/cncf/artwork/blob/master/tuf/icon/color/tuf-icon-color.svg

containerd and notary have no color icons, and black & white icons are not square

**Comment by radoslaw** [comment]
grpc has no "icon" foldernotary has no "color" folder in "icons" so images are not placed consistently

icons that aren't square:

cni white color blackcore-dns white black colorenvoy white black colorfluentd white color blackjaeger white color blackjaeger reverse color kubernetes border color black kubernetes noborder color black whitelinkerd black color whitenotary black white blackopentracing color white blackprometheus color white blackrkt black color [white is ok]tuf black color white
Rad

    On Friday, November 24, 2017, 6:48:10 AM GMT+1, Łukasz Gryglicki <notifications@github.com> wrote:  
 
 
Fluentd is not square: https://github.com/cncf/artwork/blob/master/fluentd/icon/color/fluentd-icon-color.svg
gRPC is not square: https://github.com/cncf/artwork/blob/master/grpc/color/grpc-color.svg
Same with:
Envoy: https://github.com/cncf/artwork/blob/master/envoy/icon/color/envoy-icon-color.svg
Jeager: https://github.com/cncf/artwork/blob/master/jaeger/icon/color/jaeger-icon-color.svg
TUF: https://github.com/cncf/artwork/blob/master/tuf/icon/color/tuf-icon-color.svg

containerd and notary have no color icons, and black & white icons are not square

**Comment by alexcontini** [comment]
GRPC only has one version (horizontal, stacked and icon are the same). notary is only black and white, there is no colour version.

For consistency, I cropped all svg files to the logo, so there is no extra space around them, because all the logos are different orientations I think this is the best idea. Is there a reason the artboards should all be square instead of this?

**Comment by dankohn** [comment]
There are a number of logo cases where a square icon is helpful, particularly grids and things like the top-left icon of https://prometheus.devstats.cncf.io/dashboard/db/dashboards?refresh=15m&orgId=1

I'm somewhat inclined to rename all our icon folders to square-no-text and then have @alexcontini do the positioning so they look good. gRPC would then get horizontal and square-no-text versions (but not stacked), just like the CNCF logo.

@alexcontini Could you please get Craig's opinion before we dive in. What's his GitHub username?

**Comment by alexcontini** [comment]
Hi Dan,

I have added Craig to this email. I can definitely re-crop to square
artboards, Craig, do you think it is best for the svg files to all be on
perfectly square artboards, or cropped to the actual dimensions of each
logo? Also, what is your github username?

Thank you!

Alex

**Comment by ccraigross** [comment]
Thanks for clarifying Dan.

I would suggest two versions in that case.

1. The tight artboard that goes to the edges of the artwork. This would be
the standard vector version for any purpose.
2. A uniform artboard with the logos centered similar to what we do with
member logos but we won't have the artwork extend to the edges. This would
let someone display the logos with set spacing without having to edit.

You could keep the existing version as well or replace those with #1.

On Nov 24, 2017 10:39, "Dan Kohn" <notifications@github.com> wrote:

Cc @ccraigross <https://github.com/ccraigross>

Craig, we're making the artwork available for any purpose. We're trying to
figure out best practice to make it as useful as possible. We're also doing
this investment now on the theory that we might have twice as many logos
next year.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cncf/artwork/issues/17#issuecomment-346854599>, or mute
the thread

**Comment by dankohn** [comment]
Craig, please take a more holistic look at what we're doing. We currently have:

stacked
horizontal
icon

Are you suggesting we do:

stacked
horizontal
square-no-text
square-no-text-with-border

I'm totally open to that. I'm just looking for consistency. For example, I'd like a square GRPC logo so that it doesn't get more space than other project logos.

I'm not totally convinced the with-border version is necessary, since lots of layouts already seem to apply spacing between icons.

**Comment by ccraigross** [comment]
Looking at this from a different perspective... the existing files may be
fine.

We can introduce guidelines for displaying project logos by assigning GRPC
a specific height %.

Would you be open to us exploring introducing a square asset for GRPC?


On Nov 24, 2017 13:52, "Dan Kohn" <notifications@github.com> wrote:

Craig, please take a more holistic look at what we're doing. We currently
have:

stacked
horizontal
icon

Are you suggesting we do:

stacked
horizontal
square-no-text
square-no-text-with-border

I'm totally open to that. I'm just looking for consistency. For example,
I'd like a square GRPC logo so that it doesn't get more space than other
project logos.

I'm not totally convinced the with-border version is necessary, since lots
of layouts already seem to apply spacing between icons.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cncf/artwork/issues/17#issuecomment-346882825>, or mute
the thread

**Comment by dankohn** [comment]
I'm currently inclined to redo all icons as squares and add an icon view for gRPC that is also square. Are you OK with that?

**Comment by ccraigross** [comment]
I think that makes the most sense, especially since most of the existing
assets are already acceptable.

**Comment by dankohn** [comment]
Closing and reopening as this issue derailed.
